feat(ci): publish extension to both VSCE and OVSX (#48)
This PR enhances the CI workflow to support automatic publishing of the
extension to both the **Visual Studio Code Marketplace** and **Open VSX
Registry**.

## Changes

- Integrated `vsce publish` for VS Code Marketplace publishing.
- Integrated `ovsx publish` for Open VSX publishing.
- Updated GitHub Actions workflow to automate the release process on
both platforms.

## Related 

### Issue

Resolves: #47

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,26 @@ on:
                 description: 'Tag to release'
                 required: false
                 type: string
+            pre_release:
+                description: 'Pre-release version'
+                required: false
+                type: boolean
+                default: false
+            skip_github:
+                description: 'Skip GitHub release'
+                required: false
+                type: boolean
+                default: false
+            skip_vscode:
+                description: 'Skip VSCode release'
+                required: false
+                type: boolean
+                default: false
+            skip_openvsx:
+                description: 'Skip OpenVSX release'
+                required: false
+                type: boolean
+                default: false
     push:
         tags: # Use to run the workflow when a tag is pushed
             - '*'
@@ -55,12 +75,12 @@ jobs:
             os: ${{ matrix.os }}
             platform: ${{ matrix.platform }}
             arch: ${{ matrix.arch }}
+            pre_release: ${{ inputs.pre_release }}
 
-    ci-release:
-        name: Release extension
+    ci-release-validate:
+        name: Validate release
         runs-on: ubuntu-latest
         needs: ci-compile
-
         steps:
             - name: Download all compiled releases
               uses: actions/download-artifact@v4
@@ -76,6 +96,16 @@ jobs:
                   fi
                   echo "::notice::Found artifact: $artifact_paths"
 
+    ci-release-github:
+        name: Release to GitHub
+        runs-on: ubuntu-latest
+        if: ${{ !inputs.skip_github }}
+        needs: ci-release-validate
+        steps:
+            - name: Download all compiled releases
+              uses: actions/download-artifact@v4
+              with:
+                  path: artifact
             - name: Set tag name
               id: set_tag_name
               run: |
@@ -94,3 +124,82 @@ jobs:
                   artifacts: '${{ github.workspace }}/artifact/**/*.vsix'
                   artifactErrorsFailBuild: true
                   generateReleaseNotes: true
+                  prerelease: ${{ inputs.pre_release }}
+
+    ci-release-vscode:
+        name: Release to VSCode Marketplace
+        runs-on: ubuntu-latest
+        if: ${{ !inputs.skip_vscode }}
+        needs: ci-release-validate
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+              with:
+                  sparse-checkout: |
+                      package.json
+                      package-lock.json
+            - name: Setup Node.js
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 20
+                  cache: 'npm'
+                  cache-dependency-path: package-lock.json
+            - name: Install dependencies
+              run: npm ci
+            - name: Download all compiled releases
+              uses: actions/download-artifact@v4
+              with:
+                  path: artifact
+            - name: Check if the VSCE_PAT is set
+              run: |
+                  if [ -z "${{ secrets.VSCE_PAT }}" ]; then
+                      echo "::error::VSCE_PAT is not set"
+                      exit 1
+                  fi
+            - name: Publish to VSCode Marketplace
+              run: |
+                  if [ "${{ inputs.pre_release }}" = "true" ]; then
+                      npx vsce publish --pat ${{ secrets.VSCE_PAT }} --packagePath $(find ./artifact -iname *.vsix) --pre-release
+                  else
+                      npx vsce publish --pat ${{ secrets.VSCE_PAT }} --packagePath $(find ./artifact -iname *.vsix)
+                  fi
+                  echo "::notice::Published to VSCode Marketplace successfully for pre-release: ${{ inputs.pre_release }}"
+
+    ci-release-openvsx:
+        name: Release to OpenVSX
+        runs-on: ubuntu-latest
+        if: ${{ !inputs.skip_openvsx }}
+        needs: ci-release-validate
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+              with:
+                  sparse-checkout: |
+                      package.json
+                      package-lock.json
+            - name: Setup Node.js
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 20
+                  cache: 'npm'
+                  cache-dependency-path: package-lock.json
+            - name: Install dependencies
+              run: npm ci
+            - name: Download all compiled releases
+              uses: actions/download-artifact@v4
+              with:
+                  path: artifact
+            - name: Check if the OVSX_PAT is set
+              run: |
+                  if [ -z "${{ secrets.OVSX_PAT }}" ]; then
+                      echo "::error::OVSX_PAT is not set"
+                      exit 1
+                  fi
+            - name: Publish to OpenVSX
+              run: |
+                  if [ "${{ inputs.pre_release }}" = "true" ]; then
+                      npx ovsx publish --pat ${{ secrets.OVSX_PAT }} --packagePath $(find ./artifact -iname *.vsix) --pre-release
+                  else
+                      npx ovsx publish --pat ${{ secrets.OVSX_PAT }} --packagePath $(find ./artifact -iname *.vsix)
+                  fi
+                  echo "::notice::Published to OpenVSX successfully for pre-release: ${{ inputs.pre_release }}"
